### ISSUE TITLE
incompatible with photutils >= 1.0.0

### ISSUE THREAD

**Issue by niu541412** [lukaswenzl/astrometry#2]
`AstropyDeprecationWarning: Inputing positions shaped as 2xN is deprecated and will be removed in v0.8.  Positions should be a (x, y) pixel position or a list or array of (x, y) pixel positions, e.g. [(x1, y1), (x2, y2), (x3, y3)]. [photutils.aperture.attributes]`

change line 162 & 769 of astrometry.py from
```python
positions = (sources['xcentroid'], sources['ycentroid'])
positions = (observation['xcenter'], observation['ycenter'])
```
to

```python
positions = list(np.asanyarray([sources['xcentroid'],sources['ycentroid']]).T)
positions = list(np.asanyarray([observation['xcenter'], observation['ycenter']]).T)
```
, can make it works in both versions of photutils

**Comment by lukaswenzl** [comment]
Thank you very much for raising this issue. I was able to reproduce the error and your solutions does work. 
This was caused by a change in photutils and also affects other parts of the code. The linked pull request implements the fix for all of them.

PS: sorry for the later reply it seems my notifications for this repo were not turned on...
