### ISSUE TITLE
ValueError on positions (and solution

### ISSUE THREAD

**Issue by vertighel** [lukaswenzl/astrometry#3]
To overcome
`ValueError: Input positions must be an (x, y) pixel position or a list or array of (x, y) pixel positions, e.g., [(x1, y1), (x2, y2), (x3, y3)].`

I suggest to modify lines 163 and 774 of `astrometry.py` as follows:

      #positions = (sources['xcentroid'], sources['ycentroid'])                                                                                     
      positions = zip(sources['xcentroid'], sources['ycentroid'])                                                                                   

and

     #positions = (observation['xcenter'], observation['ycenter'])                                                                                 
     positions = zip(observation['xcenter'].values, observation['ycenter'].values)

**Comment by lukaswenzl** [comment]
Thank you very much for raising this issue. I was able to reproduce the error and your solutions does work. 
This was caused by a change in photutils and also affects other parts of the code. The linked pull request implements the fix for all of them.

PS: sorry for the later reply it seems my notifications for this repo were not turned on...
